name = "Reap N' Sow"
author = "ChefMooon"
version = "1.4.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36b5b4226385e96f620d2351623de7ff787e530404816882156e7bb928be35a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
